<a href="https://colab.research.google.com/github/AlexisStdp/AlexisStdp.github.io/blob/master/Datathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://AlexisStdp:g1thUBpwdNn@github.com/ixil/datathon21.git

Cloning into 'datathon21'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (259/259), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 259 (delta 105), reused 181 (delta 62), pack-reused 0
Receiving objects: 100% (259/259), 31.67 MiB | 10.43 MiB/s, done.
Resolving deltas: 100% (105/105), done.


In [2]:
!cd datathon21/ && git pull

Already up to date.


In [3]:
!pip install --upgrade pandas

     |████████████████████████████████| 9.9MB 7.7MB/s 
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 1.2.4 which is incompatible.
  Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5


In [7]:
pd.show_versions()

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)



INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 4.19.112+
Version          : #1 SMP Thu Jul 23 08:00:38 PDT 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.4
numpy            : 1.19.5
pytz             : 2018.9
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 56.1.0
Cython           : 0.29.22
pytest           : 3.6.4
hypothesis       : None
sphinx           : 1.8.5
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 5.5.0
pandas_datareader: 0.9.0
bs4              : 4.6.3
bottleneck       : 

In [48]:
! cp datathon21/Mo/Features_Data/Amenities_features_Train.csv Amenities_features_Train.csv

In [49]:
! cp datathon21/Mo/Features_Data/Amenities_features_Test.csv Amenities_features_Test.csv

In [50]:
! cp datathon21/Mo/Features_Data/Part2_Amenities_features_Train.csv Part2_Amenities_features_Train.csv

In [51]:
! cp datathon21/Mo/Features_Data/Part2_Amenities_features_Test.csv Part2_Amenities_features_Test.csv

In [82]:
! cp /content/datathon21/kei/real_estate/transportation_distance_test.csv transportation_distance_test.csv 

In [83]:
! cp /content/datathon21/kei/real_estate/transportation_distance_train.csv transportation_distance_train.csv 

In [90]:
! python datathon21/kei/real_estate/preprocess_data.py 

Traceback (most recent call last):
  File "datathon21/kei/real_estate/preprocess_data.py", line 74, in <module>
    X_train, X_test = preprocess_data(X_train, X_test)
  File "datathon21/kei/real_estate/preprocess_data.py", line 63, in preprocess_data
    X = pd.concat([X, Z], axis=1)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py", line 298, in concat
    return op.get_result()
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/concat.py", line 516, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 3172, in get_indexer
    "Reindexing only valid with uniquely valued Index objects"
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects


In [1]:
import sklearn
import numpy as np
import tensorflow as tf
import pandas as pd
import xgboost as xgb

In [2]:
from tensorflow import keras
from tensorflow.keras import layers, regularizers, Sequential, Model, backend as K
from tensorflow.keras.layers import Input, Dense, Dropout, concatenate, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization

In [134]:
leave_out = 40000
xgb_model = xgb.XGBRegressor(random_state=42, max_depth=10, objective='reg:squarederror', learning_rate=.1)
xgb_model.fit(X_train_ready[:-leave_out], y_train[:-leave_out])

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=10, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=42, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [135]:
print(sklearn.metrics.mean_squared_error(xgb_model.predict(X_train_ready[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(xgb_model.predict(X_train_ready[leave_out:]), y_train[leave_out:], squared=False))

94940.71735703977
171599.3222388754


In [136]:
import lightgbm as lgb
params = {'num_leaves': 100}
lgb_data = lgb.Dataset(X_train_ready[:-leave_out], label=y_train[:-leave_out])
bst = lgb.train(params, lgb_data, 100)
# lgb.cv(param, train_data, num_round, nfold=5)

In [137]:
print(sklearn.metrics.mean_squared_error(bst.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(bst.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

184641.19978960682
204701.4055561699


In [25]:
extra_X = pd.read_csv('/content/datathon21/Mo/Features_Data/Amenities_features_Train.csv')
X = X_train.copy()
X['Public transport in 1km radius'] = extra_X['Public transport in 1km radius']
X['Hospital in 1km radius'] = extra_X['Hospital in 1km radius']
X['BeachDensity in 1km radius'] = extra_X['BeachDensity in 1km radius']
X['Km to CBD'] = extra_X['Km to CBD']
X['Church in 1km radius'] = extra_X['Church in 1km radius']
X['Kindergarten in 1km radius'] = extra_X['Kindergarten in 1km radius']
extra_X = pd.read_csv('/content/datathon21/Mo/Features_Data/Part2_Amenities_features_Train.csv')
X['Restaurant in 1km radius'] = extra_X['Restaurant in 1km radius']
X['Cafe in 1km radius'] = extra_X['Cafe in 1km radius']
X['Bar in 1km radius'] = extra_X['Bar in 1km radius']
X['Pub in 1km radius'] = extra_X['Pub in 1km radius']

# All

In [4]:
X_train = pd.read_csv('X_train_preprocessed.csv')
X_train

Date        Lat        long  ...  SC_tdist  FS_ttime  FS_tdist
0      1222750 -37.829457  145.130499  ...   18826.0    2587.0   16852.0
1       554800 -37.901293  145.040301  ...   15551.0    1688.0   13980.0
2       610280 -38.088126  145.488687  ...   59834.0    5454.0   58275.0
3       485815 -37.885781  144.776041  ...   24691.0    2621.0   26203.0
4       890600 -37.836286  144.943116  ...    3022.0    1627.0    4146.0
...        ...        ...         ...  ...       ...       ...       ...
84563  1471680 -37.811613  145.123794  ...   18777.0    2583.0   17163.0
84564   128480 -37.830895  145.044432  ...    9272.0    1934.0    7866.0
84565   554800 -37.823592  145.244889  ...   29091.0    2923.0   27501.0
84566  1100110 -37.818219  145.242537  ...   27252.0    3276.0   25756.0
84567   730730 -37.482672  144.599369  ...   69477.0    6072.0   71089.0

[84568 rows x 729 columns]

In [5]:
X_test = pd.read_csv('X_test_preprocessed.csv')
X_test

Date        Lat        long  ...  SC_tdist  FS_ttime  FS_tdist
0       128480 -37.872024  145.168952  ...   24330.0    2985.0   22770.0
1      1204500 -37.752083  145.053423  ...   16488.0    2883.0   18053.0
2       855195 -37.669419  144.588998  ...   45580.0    5857.0   45524.0
3      1000100 -37.756833  144.746616  ...   23606.0    4063.0   25785.0
4       670140 -37.860910  145.319344  ...   38903.0    5153.0   37319.0
...        ...        ...         ...  ...       ...       ...       ...
41648  1340280 -37.790912  144.995977  ...    8507.0    1564.0   10072.0
41649   402960 -37.973567  145.160623  ...   28590.0    2986.0   27042.0
41650  1224575 -37.870497  145.036959  ...   11454.0    1716.0    9883.0
41651   664300 -37.690474  144.553736  ...   41469.0    4873.0   43049.0
41652  1073100 -37.770674  145.063068  ...   15221.0    2328.0   16778.0

[41653 rows x 729 columns]

In [6]:
y_train = pd.read_csv('y_train.csv')
y_train.drop('Id', axis=1, inplace=True)
y_train

Price
0      500000
1      540000
2      365000
3      608000
4      787000
...       ...
84563  430000
84564  826000
84565  505000
84566  410000
84567  420000

[84568 rows x 1 columns]

In [ ]:
# xgb_model = xgb.XGBRegressor(random_state=42, max_depth=10, objective='reg:squarederror')

import lightgbm as lgb
# params = {'num_leaves': 100}
# lgb_data = lgb.Dataset(X_train_ready, label=y_train)
# bst = lgb.train(params, lgb_data, 100)

from sklearn.ensemble import GradientBoostingRegressor
# sk_gbm = GradientBoostingRegressor(random_state=42, max_depth=10)

from sklearn.ensemble import RandomForestRegressor
# regr = RandomForestRegressor(max_depth=10, random_state=42)

from sklearn.linear_model import LinearRegression
# lr = LinearRegression()

from sklearn.svm import SVR
# svr = SVR(max_iter=1000, kernel='rbf')
# svr = SVR(max_iter=1000, kernel='poly')

from sklearn.linear_model import ElasticNet
# regr = ElasticNet(random_state=42, max_iter=1000)

from sklearn.neighbors import KNeighborsRegressor
# knn = KNeighborsRegressor(5)
# knn.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
leave_out = 20000
ensemble = [xgb.XGBRegressor(random_state=42, max_depth=1, objective='reg:squarederror'),
            xgb.XGBRegressor(random_state=42, max_depth=2, objective='reg:squarederror'),
            xgb.XGBRegressor(random_state=42, max_depth=3, objective='reg:squarederror'),
            xgb.XGBRegressor(random_state=42, max_depth=2, objective='reg:squarederror', n_estimators=110),
            GradientBoostingRegressor(random_state=42, max_depth=9, n_estimators=100),
            GradientBoostingRegressor(random_state=42, max_depth=10, n_estimators=100),
            GradientBoostingRegressor(random_state=42, max_depth=11, n_estimators=100),
            RandomForestRegressor(max_depth=3, random_state=42),
            RandomForestRegressor(max_depth=2, random_state=42),
            RandomForestRegressor(max_depth=1, random_state=42),
            LinearRegression(),
            KNeighborsRegressor(1),
            ]
y_stack = []
for model in ensemble:
  print('-----------------------------------------------------')
  model.fit(X_train[:-leave_out], y_train[:-leave_out])
  y_stack.append(model.predict(X_train[-leave_out:-10000]).reshape(10000))

-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------


In [37]:
y_stack

[array([721100.75, 291940.88, 687307.06, ..., 434314.  , 992770.25,
        890954.6 ], dtype=float32),
 array([653227.49920897, 249333.24765534, 795169.82305926, ...,
        399488.753178  , 983898.56430892, 735154.23283144]),
 array([1182660.65650182,  409666.97389751,  639818.4363948 , ...,
         422078.14925178, 1182660.65650182,  789470.97694901]),
 array([ 714326.02490234,  300279.63378906,  842974.63818359, ...,
         353541.67138672, 1084650.13378906,  655735.48095703]),
 array([411666.66666667, 341333.33333333, 456833.33333333, ...,
        418666.66666667, 704666.66666667, 396000.        ]),
 array([1007871.07607589,  310110.55124887,  669098.82304487, ...,
         464298.27418546,  963939.94880675,  815075.48413917]),
 array([ 714326.02490234,  300279.63378906,  842974.63818359, ...,
         353541.67138672, 1084650.13378906,  655735.48095703])]

In [36]:
i = -4
y_stack[i] = y_stack[i].reshape(10000)

In [38]:
y_stack = np.array(y_stack).T

In [39]:
y_stack.shape

(10000, 7)

In [40]:
# king_gb = GradientBoostingRegressor(random_state=42, max_depth=3, n_estimators=10)
# king_gb.fit(y_stack, y_train[-leave_out:-5000])
# king_lr = LinearRegression()
# king_lr.fit(y_stack, y_train[-leave_out:-5000])
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(y_stack, y_train[-leave_out:-10000])

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [42]:
y_stack_val = []
for model in ensemble:
  print('-----------------------------------------------------')
  y_stack_val.append(model.predict(X[-10000:]).reshape(10000))
y_stack_val = np.array(y_stack_val).T
y_stack_val.shape

-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------


(10000, 7)

In [56]:
y_stack_big = []
for model in ensemble:
  print('-----------------------------------------------------')
  y_stack_big.append(model.predict(X[:-leave_out]).reshape(64568))
y_stack_big = np.array(y_stack_big).T
y_stack_big.shape

-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------


(64568, 7)

In [63]:
y_stack_test = []
for model in ensemble:
  print('-----------------------------------------------------')
  y_stack_test.append(model.predict(X_).reshape(41653))
y_stack_test = np.array(y_stack_test).T
y_stack_test.shape

-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------
-----------------------------------------------------


(41653, 7)

In [67]:
y_test_pred = clf.predict(y_stack_test)
y_test_pred.shape

(41653,)

In [70]:
y_test = pd.DataFrame({'Id':np.arange(41653)})
y_test['Predicted'] = y_test_pred
y_test.to_csv("./y_test.csv", index=False)

In [71]:
y_test

Id     Predicted
0          0  7.386752e+05
1          1  5.353136e+05
2          2  2.886021e+05
3          3  4.115716e+05
4          4  4.960636e+05
...      ...           ...
41648  41648  9.657294e+05
41649  41649  3.830171e+05
41650  41650  1.301770e+06
41651  41651  2.672885e+05
41652  41652  1.440183e+06

[41653 rows x 2 columns]

In [57]:
print(sklearn.metrics.mean_squared_error(clf.predict(y_stack_big), y_train[:-leave_out], squared=False))

91551.49765629192


In [45]:
print(sklearn.metrics.mean_squared_error(clf.predict(y_stack), y_train[-leave_out:-10000], squared=False))
print(sklearn.metrics.mean_squared_error(clf.predict(y_stack_val), y_train[-10000:], squared=False))

175547.89965039713
167152.78756888566


In [11]:
from sklearn.ensemble import GradientBoostingRegressor
sk_gbm = GradientBoostingRegressor(random_state=42, max_depth=10, n_estimators=100)
sk_gbm.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=10,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=42, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [15]:
print(sklearn.metrics.mean_squared_error(sk_gbm.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(sk_gbm.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

99809.31858605916
179192.73188021625


In [140]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(max_depth=10, random_state=42)
regr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=10, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [141]:
print(sklearn.metrics.mean_squared_error(regr.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(regr.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

197079.41846584243
212389.62254839923


In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
print(sklearn.metrics.mean_squared_error(lr.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(lr.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

236325.0698770643
235733.80271030831


In [144]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(5)
knn.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [145]:
print(sklearn.metrics.mean_squared_error(knn.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(knn.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

277857.0933105523
333816.989267614


In [88]:
from sklearn.svm import SVR
svr = SVR(max_iter=1000, kernel='rbf')
svr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=1000, shrinking=True, tol=0.001, verbose=False)

In [89]:
print(sklearn.metrics.mean_squared_error(svr.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(svr.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

629001.8326015454
627749.1708672319


In [94]:
from sklearn.svm import SVR
svr = SVR(max_iter=1000, kernel='poly')
svr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=1000, shrinking=True, tol=0.001, verbose=False)

In [95]:
print(sklearn.metrics.mean_squared_error(svr.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(svr.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

628964.8035077819
627711.9862902322


In [92]:
from sklearn.linear_model import ElasticNet
regr = ElasticNet(random_state=42, max_iter=1000)
regr.fit(X_train_maybe, y_train)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=10000, normalize=False, positive=False, precompute=False,
           random_state=42, selection='cyclic', tol=0.0001, warm_start=False)

In [93]:
print(sklearn.metrics.mean_squared_error(regr.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(regr.predict(X_train_maybe[leave_out:]), y_train[leave_out:], squared=False))

362781.5967797893
360125.25225522637


Let's start stacking

In [110]:
leave_out = 20000

In [22]:
# XGBOOST MODELS
# xgb_model = xgb.XGBRegressor(random_state=42, max_depth=10, objective='reg:squarederror', n_estimators=30)
# xgb_model.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

xgb_model1 = xgb.XGBRegressor(random_state=42, max_depth=9, objective='reg:squarederror', learning_rate=0.075, n_estimators=50)
xgb_model1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

# xgb_model2 = xgb.XGBRegressor(random_state=42, max_depth=10, objective='reg:squarederror', learning_rate=0.075, n_estimators=50)
# xgb_model2.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.075, max_delta_step=0,
             max_depth=9, min_child_weight=1, missing=None, n_estimators=50,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=42, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [26]:
knn = KNeighborsRegressor(5)
knn.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [37]:
knn1 = KNeighborsRegressor(2)
knn1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                    weights='uniform')

In [29]:
# LightGBM MODELS - FAST FAST !!
bst = lgb.train({'num_leaves': 100}, lgb.Dataset(X_train_maybe[:-leave_out], label=y_train[:-leave_out]), num_boost_round=100)
bst1 = lgb.train({'num_leaves': 100, 'learning_rate': 0.1, 'num_iterations': 100}, \
                 lgb.Dataset(X_train_maybe[:-leave_out], label=y_train[:-leave_out]), num_boost_round=200)
bst2 = lgb.train({'num_leaves': 100, 'learning_rate': 0.1, 'num_iterations': 110}, \
                 lgb.Dataset(X_train_maybe[:-leave_out], label=y_train[:-leave_out]), num_boost_round=300)
bst3 = lgb.train({'num_leaves': 100, 'learning_rate': 0.1, 'num_iterations': 120}, \
                 lgb.Dataset(X_train_maybe[:-leave_out], label=y_train[:-leave_out]), num_boost_round=400)
bst4 = lgb.train({'num_leaves': 100, 'learning_rate': 0.1, 'num_iterations': 130}, \
                 lgb.Dataset(X_train_maybe[:-leave_out], label=y_train[:-leave_out]), num_boost_round=500)

/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:118: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


In [36]:
print(sklearn.metrics.mean_squared_error(bst4.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(bst4.predict(X_train_maybe[-leave_out:]), y_train[-leave_out:], squared=False))

125764.86667711077
177361.96350137918


In [290]:
bst5 = lgb.train({'num_leaves': 200, 'learning_rate': 0.05, 'num_iterations': 500}, \
                 lgb.Dataset(X_train_ready[:-leave_out], label=y_train[:-leave_out]), num_boost_round=500)

/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:118: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


In [291]:
print(sklearn.metrics.mean_squared_error(bst5.predict(X_train_ready[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(bst5.predict(X_train_ready[-leave_out:]), y_train[-leave_out:], squared=False))

65347.59679381143
176652.16909470037


In [115]:
# sklearn GB-reg
sk_gbm = GradientBoostingRegressor(random_state=42, max_depth=10)
sk_gbm.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
sk_gbm1 = GradientBoostingRegressor(random_state=42, max_depth=11)
sk_gbm1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
sk_gbm1 = GradientBoostingRegressor(random_state=42, max_depth=11, n_estimators=100)
sk_gbm1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=11,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=42, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [38]:
# sklearn RF-reg
regr = RandomForestRegressor(max_depth=10, random_state=42, n_estimators=100)
regr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
regr1 = RandomForestRegressor(max_depth=10, random_state=42, n_estimators=150)
regr1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=10, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=150, n_jobs=None, oob_score=False,
                      random_state=42, verbose=0, warm_start=False)

In [39]:
# sklearn LR
lr = LinearRegression()
lr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [129]:
# sklearn ElasticNet
enet = ElasticNet(random_state=42, max_iter=1000, alpha=.8)
enet.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
enet1 = ElasticNet(random_state=42, max_iter=1000, alpha=.9, l1_ratio=.9)
enet1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
enet2 = ElasticNet(random_state=42, max_iter=1000)
enet2.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4302156120694931.0, tolerance: 1102078172617.1133
  positive)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4784674329586068.0, tolerance: 1102078172617.1133
  positive)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3059636918434583.0, tolerance: 1102078172617.1133
  positive)


ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=42, selection='cyclic', tol=0.0001, warm_start=False)

In [134]:
# sklearn SVR
svr = SVR(max_iter=1000, kernel='rbf')
svr.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])
svr1 = SVR(max_iter=1000, kernel='poly')
svr1.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=1000, shrinking=True, tol=0.001, verbose=False)

In [43]:
xgb_model = xgb.XGBRegressor(random_state=42, max_depth=10, objective='reg:squarederror', learning_rate=.1)
xgb_model.fit(X_train_maybe[:-leave_out], y_train[:-leave_out])

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=10, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=42, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [44]:
ensemble = [xgb_model, xgb_model1, bst, bst1, bst2, bst3, bst4, sk_gbm, \
            regr, regr1,# regr2, regr3, \
            knn, knn1,
            lr] #, enet, enet1, enet2, svr, svr1]

In [43]:
ensemble = [xgb_model, sk_gbm, regr, lr, knn]

In [56]:
y_stack = []
for m in ensemble:
  y_stack.append(m.predict(X_train_maybe[-leave_out:-10000]))

In [57]:
y_stack

[array([789017.44, 933341.44, 442057.72, ..., 394445.34, 948606.06,
        798141.2 ], dtype=float32),
 array([801385.9 , 910252.2 , 423095.88, ..., 412414.  , 900564.06,
        805068.2 ], dtype=float32),
 array([775190.94385082, 954042.23498704, 471174.40821308, ...,
        383837.33211987, 986435.52273157, 688721.73273023]),
 array([775190.94385082, 954042.23498704, 471174.40821308, ...,
        383837.33211987, 986435.52273157, 688721.73273023]),
 array([773186.33271161, 951554.69402617, 466027.57610934, ...,
        383866.72442383, 979126.4573706 , 680618.33408751]),
 array([768817.60789738, 937702.18296132, 464516.00766099, ...,
        386605.25518921, 969442.27655215, 681353.21328279]),
 array([778133.09060971, 938513.13271812, 463048.83306617, ...,
        384354.24669166, 970253.22630895, 666695.98064512]),
 array([818829.61574743, 923912.19106202, 440310.89899836, ...,
        401275.37690746, 923444.97207388, 822167.11070327]),
 array([919222.38597678, 923669.79387784, 

In [61]:
i = -3
y_stack[i] = y_stack[i].reshape(30000,)

In [62]:
y_stack = np.array(y_stack)

In [63]:
y_stack = y_stack.T
y_stack.shape

(30000, 13)

In [64]:
# king_gb = GradientBoostingRegressor(random_state=42, max_depth=3, n_estimators=10)
# king_gb.fit(y_stack, y_train[-leave_out:-5000])
# king_lr = LinearRegression()
# king_lr.fit(y_stack, y_train[-leave_out:-5000])
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(y_stack, y_train[-leave_out:-10000])

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 466271699074935.94, tolerance: 430581887520.2816
  positive)


Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [65]:
y_stack_val = []
for m in ensemble:
  y_stack_val.append(m.predict(X_train_maybe[-10000:]))

In [68]:
i = -3
y_stack_val[i] = y_stack_val[i].reshape(10000,)

In [69]:
y_stack_val = np.array(y_stack_val).T

In [70]:
y_stack_val.shape

(10000, 13)

In [71]:
print(sklearn.metrics.mean_squared_error(clf.predict(y_stack), y_train[-leave_out:-10000], squared=False))
print(sklearn.metrics.mean_squared_error(clf.predict(y_stack_val), y_train[-10000:], squared=False))

176308.7637188863
172291.4185564711


In [73]:
clf.coef_

array([ 0.37611982, -0.14216703,  0.26789151,  0.        ,  0.18462019,
       -0.10945193,  0.28145413,  0.15571935, -0.09086701,  0.04828178,
       -0.00137279,  0.00260919,  0.02074448])

In [78]:
extra_X = pd.read_csv('/content/datathon21/Mo/Features_Data/Amenities_features_Train.csv')

In [85]:
extra_X.columns

Index(['Unnamed: 0', 'Center_point', 'lat', 'long',
       'Public transport in 1km radius', 'Hospital in 1km radius',
       'Church in 1km radius', 'Kindergarten in 1km radius',
       'BeachDensity in 1km radius', 'Km to CBD'],
      dtype='object')

In [89]:
xgb_model2 = xgb.XGBRegressor(random_state=42, max_depth=10, objective='reg:squarederror', learning_rate=0.075, n_estimators=50)
xgb_model2.fit(X[:-leave_out], y_train[:-leave_out])

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.075, max_delta_step=0,
             max_depth=10, min_child_weight=1, missing=None, n_estimators=50,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=42, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [93]:
sk_gbm1 = GradientBoostingRegressor(random_state=42, max_depth=10, n_estimators=100)
sk_gbm1.fit(X[:-leave_out], y_train[:-leave_out])

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=10,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=42, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [94]:
print(sklearn.metrics.mean_squared_error(sk_gbm.predict(X_train_maybe[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklea7rn.metrics.mean_squared_error(sk_gbm.predict(X_train_maybe[-leave_out:]), y_train[-leave_out:], squared=False))

99809.31858605916
186200.24158278774


In [95]:
print(sklearn.metrics.mean_squared_error(sk_gbm1.predict(X[:-leave_out]), y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(sk_gbm1.predict(X[-leave_out:]), y_train[-leave_out:], squared=False))

97135.85793303559
192130.0940298709


In [ ]:
def all_models():
  0

NN

In [96]:
def nn(input_dim, output_dim, hidden_layers = 3, nodes = 100, l2_regularization = 0.0,
       s = 0.05, random = False, learning_rate = 0.001):
  input_layer = Input(shape=(input_dim, ), name='Input_Layer')
  l = Dense(nodes, activation = 'relu', 
            kernel_initializer = tf.compat.v1.keras.initializers.RandomUniform(minval=-s, maxval=s),
            kernel_regularizer = regularizers.l2(l2_regularization),
            bias_regularizer = regularizers.l2(l2_regularization), 
            trainable=not(random), name=f'ReLU_Layer_{0}')(input_layer)
  for i in range(hidden_layers - 1):
    l = Dense(nodes, activation = 'relu', 
            kernel_initializer = tf.compat.v1.keras.initializers.RandomUniform(minval=-s, maxval=s),
            kernel_regularizer = regularizers.l2(l2_regularization),
            bias_regularizer = regularizers.l2(l2_regularization), 
            trainable=not(random), name=f'ReLU_Layer_{i+1}')(l)
  l = Dense(output_dim, activation='linear',
            kernel_initializer = tf.compat.v1.keras.initializers.RandomUniform(minval=-s, maxval=s),
            bias_initializer = tf.compat.v1.keras.initializers.RandomUniform(minval=-s, maxval=s), 
            kernel_regularizer = regularizers.l2(l2_regularization),
            name = f"Output_Layer")(l)
  model = Model(inputs=[input_layer], outputs=l)
  loss_fct = 'MSE'
  model.compile(optimizer = tf.keras.optimizers.Adam(lr = learning_rate),
                loss = loss_fct, metrics = ['MSE'])
  return model

def nn_(nodes = 10):
  model = keras.Sequential()
  model.add(layers.Dense(nodes, activation="relu"))
  model.add(layers.Dense(nodes, activation="relu"))
  model.add(layers.Dense(1))
  model.compile(tf.keras.optimizers.Adam(0.01), 'MSE')
  return model

In [97]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((-1,1))
nn_x_train = scaler.fit_transform(X_train_maybe)
nn_y_train = scaler.fit_transform(y_train)

In [98]:
nn_y_train.shape

(84568, 1)

In [75]:
nn_x_train

array([[-0.06047878,  0.0217442 , -0.98773105, ...,  0.6       ,
        -0.33333333, -1.        ],
       [-0.23069779, -0.09976711, -0.90521631, ..., -0.5       ,
        -0.33333333,  0.33333333],
       [-0.67340978,  0.50428172, -0.96086765, ..., -0.725     ,
        -0.66666667,  0.33333333],
       ...,
       [-0.04658093,  0.1758466 , -0.94948077, ...,  0.        ,
        -0.33333333,  0.33333333],
       [-0.03384935,  0.17267753, -0.94290526, ...,  0.        ,
        -1.        ,  1.        ],
       [ 0.76124877, -0.69377365, -0.9485185 , ..., -0.125     ,
         0.66666667,  0.33333333]])

In [76]:
nn_x_train.shape

(84568, 23)

In [77]:
leave_out = 50000

In [334]:
nn_model = nn(23, 1, 2, 40, learning_rate=0.001, l2_regularization=0.001*0)
# nn_model = nn_(100)
# nn_model.fit(np.asarray(X_train_maybe[:-leave_out]).astype('float32'),
#              np.asarray(y_train[:-leave_out]).astype('float32'),
#              batch_size=None, epochs=10)
# nn_model.fit(np.asarray(nn_x_train[:-leave_out]).astype('float32'),
#              np.asarray(nn_y_train[:-leave_out]).astype('float32'),
#              batch_size=None, epochs=10)
nn_model.fit(nn_x_train[:-leave_out],
             nn_y_train[:-leave_out],
             batch_size=64, epochs=10)

Epoch 1/10
541/541 [==============================] - 2s 2ms/step - loss: 0.1456 - MSE: 0.1456
Epoch 2/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0286 - MSE: 0.0286
Epoch 3/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0262 - MSE: 0.0262
Epoch 4/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0240 - MSE: 0.0240
Epoch 5/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0215 - MSE: 0.0215
Epoch 6/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0216 - MSE: 0.0216
Epoch 7/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0204 - MSE: 0.0204
Epoch 8/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0184 - MSE: 0.0184
Epoch 9/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0183 - MSE: 0.0183
Epoch 10/10
541/541 [==============================] - 1s 2ms/step - loss: 0.0177 - MSE: 0.0177


In [335]:
temp1 = scaler.inverse_transform(nn_model.predict(nn_x_train[:-leave_out]))
temp2 = scaler.inverse_transform(nn_model.predict(nn_x_train[-leave_out:]))

NN bagging

In [104]:
nn_ensemble = []
for _ in range(10):
  temp = nn(714, 1, 2, 200, learning_rate=0.0005, l2_regularization=0.001*0)
  temp.fit(nn_x_train[:-leave_out],
              nn_y_train[:-leave_out],
              batch_size=64, epochs=10, verbose=0)
  nn_ensemble.append(temp)

In [124]:
for _ in range(40):
  temp = nn(23, 1, 2, 200, learning_rate=0.0005, l2_regularization=0.001*0)
  temp.fit(nn_x_train[:-leave_out],
              nn_y_train[:-leave_out],
              batch_size=64, epochs=50, verbose=0)
  nn_ensemble.append(temp)

In [98]:
# nn_ensemble1 = []  ## with l2
# for _ in range(10):
#   temp = nn(23, 1, 2, 200, learning_rate=0.0005, l2_regularization=0.005)
#   temp.fit(nn_x_train[:-leave_out],
#               nn_y_train[:-leave_out],
#               batch_size=64, epochs=50, verbose=0)
#   nn_ensemble1.append(temp)

In [110]:
nn_ensemble1 = []  ## with l2
for _ in range(10):
  temp = nn(23, 1, 3, 100, learning_rate=0.0005, l2_regularization=0.005*0)
  temp.fit(nn_x_train[:-leave_out],
              nn_y_train[:-leave_out],
              batch_size=64, epochs=30, verbose=0)
  nn_ensemble1.append(temp)

In [118]:
nn_ensemble2 = []  ## with l2
for _ in range(10):
  temp = nn(23, 1, 1, 100, learning_rate=0.0005, l2_regularization=0.005*0)
  temp.fit(nn_x_train[:-leave_out],
              nn_y_train[:-leave_out],
              batch_size=64, epochs=30, verbose=0)
  nn_ensemble2.append(temp)

In [106]:
pred = np.zeros((44568,1))
pred_val = np.zeros((leave_out,1))
for n in nn_ensemble:
  pred += scaler.inverse_transform(n.predict(nn_x_train[:-leave_out]))
  pred_val += scaler.inverse_transform(n.predict(nn_x_train[-leave_out:]))
pred /= 10
pred_val /= 10

In [128]:
pred *= 10
pred_val *= 10
pred /= 50
pred_val /= 50

In [111]:
pred1 = np.zeros((34568,1))
pred_val1 = np.zeros((leave_out,1))
for n in nn_ensemble1:
  pred1 += scaler.inverse_transform(n.predict(nn_x_train[:-leave_out]))
  pred_val1 += scaler.inverse_transform(n.predict(nn_x_train[-leave_out:]))
pred1 /= 10
pred_val1 /= 10

In [119]:
pred2 = np.zeros((34568,1))
pred_val2 = np.zeros((leave_out,1))
for n in nn_ensemble2:
  pred2 += scaler.inverse_transform(n.predict(nn_x_train[:-leave_out]))
  pred_val2 += scaler.inverse_transform(n.predict(nn_x_train[-leave_out:]))
pred2 /= 10
pred_val2 /= 10

In [122]:
pred3 = (pred + pred1 + pred2) / 3
pred_val3 = (pred_val + pred_val1 + pred_val2) / 3

In [107]:
print(sklearn.metrics.mean_squared_error(pred,
                                         y_train[:-leave_out], squared=False))
print(sklearn.metrics.mean_squared_error(pred_val,
                                         y_train[-leave_out:], squared=False))

220543.0371615809
222174.52905634907


In [96]:
for i,_ in enumerate(nn_ensemble):
  print(sklearn.metrics.mean_squared_error(scaler.inverse_transform(nn_ensemble[i].predict(nn_x_train[:-leave_out])),
                                          y_train[:-leave_out], squared=False) < 165000)
  print(sklearn.metrics.mean_squared_error(scaler.inverse_transform(nn_ensemble[i].predict(nn_x_train[-leave_out:])),
                                          y_train[-leave_out:], squared=False) < 205000)

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False


In [114]:
!cd datathon21/ && git pull

remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 16 (delta 5), reused 15 (delta 4), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/ixil/datathon21
   9f196e4..3309823  main       -> origin/main
Updating 9f196e4..3309823
Fast-forward
 kei/real_estate/Output XGB prediction.ipynb       |   103 +
 kei/real_estate/X_test.csv                        | 41654 ++++++++++
 kei/real_estate/X_train.csv                       | 84569 ++++++++++++++++++++
 kei/real_estate/latitude londitude features.ipynb |   292 +
 kei/real_estate/preprocess_data.py                |    15 +
 kei/real_estate/y_train.csv                       | 84569 ++++++++++++++++++++
 6 files changed, 211202 insertions(+)
 create mode 100644 kei/real_estate/Output XGB prediction.ipynb
 create mode 100644 kei/real_estate/X_test.csv
 create mode 100644 kei/real_estate/X_train.csv
 create mode 100644 kei/rea

In [1]:
!pip install --upgrade pandas

Requirement already up-to-date: pandas in /usr/local/lib/python3.7/dist-packages (1.2.4)
